--- 
- name: Conditional Playbook
  hosts: all
  become: true
  become_method: sudo
  tasks: 
  - name: Information
    ansible.builtin.debug:
      var: ansible_facts['distribution']
  - name: Create a new database Ubuntu
    when: 
    - ansible_facts['distribution'] == "Ubuntu"  
      apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu trusty main' state=present
      apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
      apt: name=mariadb-server state=latest update_cache=yes
      ignore_errors: yes      
      notify: Restart mariadb Ubuntu
  - name: Add users to Amazon
    when: 
    - ansible_facts['distribution'] == "Amazon" 
    ansible.builtin.user:
      name: "{{ item }}"
    with_items:
    - Bob
    - ben
    - lisa
    - katty
  - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
    when: 
    - ansible_facts['distribution'] == "Amazon"   
    user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
  - name: Download csv file
    when: 
    - ansible_facts['distribution'] == "Amazon" 
    ignore_errors: true
    ansible.builtin.get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
      with_items:
       - { dest: '/home/Bob/',mode: '0755'}
       - { dest: '/home/ben/' , mode: '0755'}
       - { dest: '/home/lisa/',mode: '0755'}
       - { dest: '/home/katty/',mode: '0755'}

  handlers:
  - name: Restart mariadb Ubuntu
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - name: Restart MariaDB 10.3
      service: name=mysql state=restarted 


  
  